### PR TITLE
[WIP] Rosmodelparser

### PR DESCRIPTION
**Pull request by ipa-hsd**
Depends on https://github.com/rosin-project/rosgraph_monitor/pull/6

Added `ModelParser` in `rosmodel2owl.py`

The parse result is
```
['f2_v3_r3', ['move_base', ['controller_frequency', 'move_base.move_base.move_base.controller_frequency', 20.0], ['max_vel_x', 'move_base.move_base.move_base.max_vel_x', 0.75], ['inflation_radius', 'move_base.move_base.move_base.inflation_radius', 0.6]], ['qa_safety', 'Double', 0.0], ['qa_energy', 'Double', 0.0]]
- global_parameters: [['qa_safety', 'Double', 0.0], ['qa_energy', 'Double', 0.0]]
  [0]:
    ['qa_safety', 'Double', 0.0]
    - value_type: ['Double']
    - param_name: ['qa_safety']
    - param_value: [0.0]
  [1]:
    ['qa_energy', 'Double', 0.0]
    - g_value_type: ['Double']
    - param_name: ['qa_energy']
    - param_value: [0.0]
- interfaces: [['move_base', ['controller_frequency', 'move_base.move_base.move_base.controller_frequency', 20.0], ['max_vel_x', 'move_base.move_base.move_base.max_vel_x', 0.75], ['inflation_radius', 'move_base.move_base.move_base.inflation_radius', 0.6]]]
  [0]:
    ['move_base', ['controller_frequency', 'move_base.move_base.move_base.controller_frequency', 20.0], ['max_vel_x', 'move_base.move_base.move_base.max_vel_x', 0.75], ['inflation_radius', 'move_base.move_base.move_base.inflation_radius', 0.6]]
    - interface_name: ['move_base']
    - parameters: [['controller_frequency', 'move_base.move_base.move_base.controller_frequency', 20.0], ['max_vel_x', 'move_base.move_base.move_base.max_vel_x', 0.75], ['inflation_radius', 'move_base.move_base.move_base.inflation_radius', 0.6]]
      [0]:
        ['controller_frequency', 'move_base.move_base.move_base.controller_frequency', 20.0]
        - param_name: ['controller_frequency']
        - param_path: ['move_base.move_base.move_base.controller_frequency']
        - param_value: [20.0]
      [1]:
        ['max_vel_x', 'move_base.move_base.move_base.max_vel_x', 0.75]
        - param_name: ['max_vel_x']
        - param_path: ['move_base.move_base.move_base.max_vel_x']
        - param_value: [0.75]
      [2]:
        ['inflation_radius', 'move_base.move_base.move_base.inflation_radius', 0.6]
        - param_name: ['inflation_radius']
        - param_path: ['move_base.move_base.move_base.inflation_radius']
        - param_value: [0.6]
- system_name: ['f2_v3_r3']
```
But after running the script, I get an error:
```
Traceback (most recent call last):
  File "/mros1_reasoner_ws/src/mros1_reasoner/mros1_reasoner/scripts/rosmodel2owl.py", line 65, in <module>
    namespace=onto, isQAtype=onto.search_one(iri="*energy"), hasValue=energy_attr.param_value[0])
TypeError: 'NoneType' object is not callable
```
Is that the line returns a null object?
```
fd = tomasys.FunctionDesign(sys_name, namespace=onto)
```

### CODE REVIEW

**Comment by ipa-hsd** [comment]
@chcorbato @ipa-nhg

**Comment by ipa-hsd** [comment]
> We could search for a pkg path, but I could not find the repository#branch from where you added the file f2_v3_r3.rossystem

It seems that [metacontrol_models_experiment](https://github.com/rosin-project/rosin-experiments/tree/master/metacontrol_models_experiment) is neither a ROS nor Python package. For testing, I just created a `resources` folder inside `mros1_reasoner` package. How do you suggest to find it?

**Comment by ipa-hsd** [comment]
@chcorbato I ran the script again after your fix in https://github.com/rosin-project/mros1_reasoner/pull/34/commits/3e87cd2b4d7b7aed9e665800d3df12d4b26fb1ba. Please take a look at the output file: https://github.com/rosin-project/mros1_reasoner/pull/34/commits/f4abd644b28e03b891c9be392b989fd6b747410d
I have also added the `.rossystem` file

**Comment by chcorbato** [comment]
> @chcorbato I ran the script again after your fix in [3e87cd2](https://github.com/rosin-project/mros1_reasoner/commit/3e87cd2b4d7b7aed9e665800d3df12d4b26fb1ba). Please take a look at the output file: [f4abd64](https://github.com/rosin-project/mros1_reasoner/commit/f4abd644b28e03b891c9be392b989fd6b747410d)
> I have also added the `.rossystem` file

I misunderstood how the `os.path.join` works.

@ipa-nhg @ipa-hsd 
I think we should try avoid copying files from one pkg to another (from `rosin-experiments` to `metacontrol_move_base_experiments` to `mros1_reasoner`)
Automate this somehow? Maybe search for rospackage folders?

**Comment by ipa-nhg** [comment]
@chcorbato @ipa-hsd

what about move the rossystem files to the Ros packages that contains their deployed launch file?

This means move all the files to this repo https://github.com/rosin-project/metacontrol_move_base_configurations , where for example the `f2_v3_r3.rossystem` will be within the ROS package `f2_v3_r3`. Remember this repository has to be in your workspace to make the `rosgraph_manipular` working  and I could automate the creation of the rossystem files within the ROS package with the [bash script ](https://github.com/rosin-project/rosin-experiments/blob/master/metacontrol_models_experiment/MoveBaseConfigurations/create_config_combination_move_base.sh).

make this sense for you?

**Comment by chcorbato** [comment]
> @chcorbato @ipa-hsd
> 
> what about move the rossystem files to the Ros packages that contains their deployed launch file?
> 
> This means move all the files to this repo https://github.com/rosin-project/metacontrol_move_base_configurations , where for example the `f2_v3_r3.rossystem` will be within the ROS package `f2_v3_r3`. Remember this repository has to be in your workspace to make the `rosgraph_manipular` working and I could automate the creation of the rossystem files within the ROS package with the [bash script ](https://github.com/rosin-project/rosin-experiments/blob/master/metacontrol_models_experiment/MoveBaseConfigurations/create_config_combination_move_base.sh).
> 
> make this sense for you?

Makes total sense.

The practical problem we have for our setup is that our current setup require 2 different ROS workspaces:
- WS for the OWL related stuff (transformation rossystem2owl file, `mros1_reasoner`) because it needs ROS and Python3
- WS for the mobile_base application wiht the launchfiles
The first one needs to find the .rossystem files to create the OWL, whereas the 2nd needs to to find where to put the generated launch files

With the solution you propose, how can we find the rossystem files for OWL? Currently I'm using `rospack` in my python code. How can I finf packages that are in a different WS?
Alternatively, we could use something different than `rospack` to find the files...

Please tell me if it is confusing (not sure I have explained myself)

any ideas @ipa-nhg @ipa-hsd @marioney ?

**Comment by ipa-nhg** [comment]
@chcorbato what about use environment variables? to define the path of the python 3 WS and the WS that contains the move_base_application?

alternatively we could use ros parameters but it is adding more complexity

**Comment by ipa-hsd** [comment]
Maybe a lame suggestion, but since there are no executables in the folder and just .rossystem files, would it make sense to directly read from the URL?

**Comment by ipa-nhg** [comment]
> Maybe a lame suggestion, but since there are no executables in the folder and just .rossystem files, would it make sense to directly read from the URL? The path to the URL can be an `arg` to the `rosmodel2owl.py`

good idea, but not sure if this will delay the reconfiguration.. but maybe copy all of them to the /tmp folder when you start the application, can solve the issue.

 I made that in the past to solve a similar issue and works perfectly: ( See: https://github.com/ipa320/cob_driver/blob/kinetic_dev/cob_mimic/src/mimic_node.cpp#L153-L157 )

**Comment by chcorbato** [comment]
> > Maybe a lame suggestion, but since there are no executables in the folder and just .rossystem files, would it make sense to directly read from the URL? The path to the URL can be an `arg` to the `rosmodel2owl.py`
> 
> good idea, but not sure if this will delay the reconfiguration.. but maybe copy all of them to the /tmp folder when you start the application, can solve the issue.
> 
> I made that in the past to solve a similar issue and works perfectly: ( See: https://github.com/ipa320/cob_driver/blob/kinetic_dev/cob_mimic/src/mimic_node.cpp#L153-L157 )

Sounds good to me. Do you have time to do it @ipa-hsd @nadia?

**Comment by ipa-hsd** [comment]
Yes, will let know you once I get something.

**Comment by chcorbato** [comment]
I move this to a new issue:
https://github.com/rosin-project/rosin-experiments/issues/13

**Pull request merged**
